parameters:
#    scruno_auth.example.class: Scruno\AuthBundle\Example

services:
#    scruno_auth.example:
#        class: %scruno_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
