Scruno\AuthBundle\Entity\User:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }
