admin_board_column:
    pattern:  /
    defaults: { _controller: "ScrunoBoardBundle:BoardColumn:index" }

admin_board_column_show:
    pattern:  /{id}/show
    defaults: { _controller: "ScrunoBoardBundle:BoardColumn:show" }

admin_board_column_new:
    pattern:  /new
    defaults: { _controller: "ScrunoBoardBundle:BoardColumn:new" }

admin_board_column_create:
    pattern:  /create
    defaults: { _controller: "ScrunoBoardBundle:BoardColumn:create" }
    requirements: { _method: post }

admin_board_column_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ScrunoBoardBundle:BoardColumn:edit" }

admin_board_column_update:
    pattern:  /{id}/update
    defaults: { _controller: "ScrunoBoardBundle:BoardColumn:update" }
    requirements: { _method: post|put }

admin_board_column_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ScrunoBoardBundle:BoardColumn:delete" }
    requirements: { _method: post|delete }
