<?php

namespace Scruno\BoardBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BoardColumnController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Scruno\BoardBundle\Controller\BoardColumnController();
        return $instance;
    }
}
