<?php

namespace Proxies\__CG__\Scruno\BoardBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TaskStatus extends \Scruno\BoardBundle\Entity\TaskStatus implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setIsComplete($isComplete)
    {
        $this->__load();
        return parent::setIsComplete($isComplete);
    }

    public function getIsComplete()
    {
        $this->__load();
        return parent::getIsComplete();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getIsDefault()
    {
        $this->__load();
        return parent::getIsDefault();
    }

    public function setIsDefault($isDefault)
    {
        $this->__load();
        return parent::setIsDefault($isDefault);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setPosition($position)
    {
        $this->__load();
        return parent::setPosition($position);
    }

    public function getIsInProgress()
    {
        $this->__load();
        return parent::getIsInProgress();
    }

    public function setIsInProgress($isInProgress)
    {
        $this->__load();
        return parent::setIsInProgress($isInProgress);
    }

    public function getIsStopped()
    {
        $this->__load();
        return parent::getIsStopped();
    }

    public function setIsStopped($isStopped)
    {
        $this->__load();
        return parent::setIsStopped($isStopped);
    }

    public function getIsBlocked()
    {
        $this->__load();
        return parent::getIsBlocked();
    }

    public function setIsBlocked($isBlocked)
    {
        $this->__load();
        return parent::setIsBlocked($isBlocked);
    }

    public function getShowInBoard()
    {
        $this->__load();
        return parent::getShowInBoard();
    }

    public function setShowInBoard($showInBoard)
    {
        $this->__load();
        return parent::setShowInBoard($showInBoard);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'position', 'isComplete', 'isDefault', 'isInProgress', 'isStopped', 'isBlocked', 'showInBoard');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}