Scruno\BoardBundle\Entity\Backlog:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        startDate:
            type: datetime
            column: start_date
        endDate:
            type: datetime
            column: end_date
    lifecycleCallbacks: {  }
