Scruno\BoardBundle\Entity\TaskType:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        color:
            type: string
            length: '6'
    lifecycleCallbacks: {  }
